// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptntxlxhjfoxzszcwpbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0bnR4bHhoamZveHpzemN3cGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMzY1ODMsImV4cCI6MjA2NTYxMjU4M30.aomIK_vxLxRBoVUpWUgiXM62vTBxl6axQ4BBimi0O98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);